// examples/react/src/App.tsx
import {
	BindingFieldInput,
	FieldErrors,
	registerGlobalValidator,
	useForm,
} from "@ez-kits/form-react";
import { zodValidator } from "@ez-kits/form-zod-validator";
import { useState } from "react";
import { z } from "zod";
import "./App.css";
import reactLogo from "./assets/react.svg";
import viteLogo from "/vite.svg";

function App() {
	const [count, setCount] = useState(0);

	return (
		<>
			<div>
				<a href="https://vitejs.dev" target="_blank">
					<img src={viteLogo} className="logo" alt="Vite logo" />
				</a>
				<a href="https://react.dev" target="_blank">
					<img src={reactLogo} className="logo react" alt="React logo" />
				</a>
			</div>
			<h1>Vite + React</h1>
			<div className="card">
				<button onClick={() => setCount((count) => count + 1)}>
					count is {count}
				</button>
				<p>
					Edit <code>src/App.tsx</code> and save to test HMR
				</p>
			</div>
			<p className="read-the-docs">
				Click on the Vite and React logos to learn more
			</p>
			<LoginPage />
		</>
	);
}

export default App;

interface LoginForm {
	username: string;
	password: string;
	addresses: {
		lineOne: string;
		lineTwo: string;
	}[];
	job: {
		position: string;
		salary: number;
	};
}

declare module "@ez-kits/form-react" {
	interface GlobalRegister {
		validator: typeof zodValidator;
	}
}

registerGlobalValidator(zodValidator);

function LoginPage() {
	const form = useForm<LoginForm>({
		name: "abc",
	});

	return (
		<form.Form>
			<form {...form.getFormProps()}>
				<form.Observe>
					{({ values }) => <span>{JSON.stringify(values)}</span>}
				</form.Observe>
				<form.ObserveField name="addresses">
					{({ value: addresses }) => <span>{addresses?.join(",")}</span>}
				</form.ObserveField>
				<br />
				<form.Field name="username">
					<BindingFieldInput>
						<input data-testid="usernameInput" />
					</BindingFieldInput>
				</form.Field>
				<form.Field
					name="password"
					label="Password"
					validationSchema={z
						.string()
						.min(1, "Password is required")
						.regex(
							new RegExp("^(?=.*[A-Za-z])(?=.*d)[A-Za-zd]{8,}$"),
							"Password must contain 8 or more characters with at least one letter and one number"
						)
						.default("")}
				>
					<BindingFieldInput>
						<input data-testid="passwordInput" type="password" />
					</BindingFieldInput>
					<FieldErrors>
						{(errors) => errors?.map((error) => error.messages)}
					</FieldErrors>
				</form.Field>

				<br />

				<form.FieldArray name="addresses">
					{({ fieldArray, fieldsInfo }) => {
						return (
							<>
								{fieldsInfo.map((field) => {
									return (
										<div key={field.key}>
											<fieldArray.Field index={field.index} name="lineOne">
												<BindingFieldInput>
													<input />
												</BindingFieldInput>

												<FieldErrors>
													{(errors) => errors?.map((error) => error.messages)}
												</FieldErrors>
											</fieldArray.Field>
											<br />
											<fieldArray.Field
												index={field.index}
												name="lineTwo"
												label="Line two"
												validationSchema={z.string()}
											>
												<BindingFieldInput>
													<input />
												</BindingFieldInput>

												<FieldErrors>
													{(errors) => errors?.map((error) => error.messages)}
												</FieldErrors>
											</fieldArray.Field>
										</div>
									);
								})}
								<br />
								<button
									onClick={() =>
										fieldArray.push({
											lineOne: "abc",
											lineTwo: "def",
										})
									}
								>
									Add new
								</button>
								<button
									onClick={() =>
										fieldArray.insert(2, {
											lineOne: "def",
											lineTwo: "asdfasdf",
										})
									}
								>
									Insert
								</button>
								<button onClick={() => fieldArray.pop()}>Pop</button>
								<button onClick={() => fieldArray.swap(0, 1)}>Swap</button>
							</>
						);
					}}
				</form.FieldArray>
				<form.Field name="job">
					{({ field, value }) => (
						<div>
							<field.Field name="position">{({ value }) => value}</field.Field>
						</div>
					)}
				</form.Field>
			</form>
		</form.Form>
	);
}

// examples/solid/src/App.tsx
import {
	FieldErrors,
	registerGlobalValidator,
	useForm,
} from "@ez-kits/form-solid";
import { createUniqueId, For, type Component } from "solid-js";

import { zodValidator } from "@ez-kits/form-zod-validator";
import { z } from "zod";
import styles from "./App.module.css";
import logo from "./logo.svg";

const App: Component = () => {
	return (
		<div class={styles.App}>
			<header class={styles.header}>
				<img src={logo} class={styles.logo} alt="logo" />
				<p>
					Edit <code>src/App.tsx</code> and save to reload.
				</p>
				<a
					class={styles.link}
					href="https://github.com/solidjs/solid"
					target="_blank"
					rel="noopener noreferrer"
				>
					Learn Solid
				</a>
				<LoginPage />
			</header>
		</div>
	);
};

export default App;

interface LoginForm {
	username: string;
	password: string;
	addresses: { city: string }[];
}

declare module "@ez-kits/form-solid" {
	interface GlobalRegister {
		validator: typeof zodValidator;
	}
}

registerGlobalValidator(zodValidator);

function LoginPage() {
	const form = useForm<LoginForm>({
		initialValues: {
			username: "",
			password: "",
			addresses: [],
		},
		validationSchema: z.object({
			username: z.string().min(1, "This field is required"),
			password: z.string().min(1, "This field is required"),
			addresses: z.array(
				z.object({
					city: z.string().min(1, "This field is required"),
				})
			),
		}),
	});

	form.on("error", (errors) => {
		console.log(errors);
	});

	return (
		<form.Form>
			<form.Observe>
				{({ values }) => <span>{JSON.stringify(values())}</span>}
			</form.Observe>
			<form {...form.getFormProps()}>
				<form.Field name="username">
					{({ field }) => (
						<input data-testid="usernameInput" {...field.getInputProps()} />
					)}
				</form.Field>

				<form.Field name="password">
					{({ field }) => (
						<input
							data-testid="passwordInput"
							type="password"
							{...field.getInputProps()}
						/>
					)}
				</form.Field>
				<form.FieldArray name="addresses">
					{({ fieldArray, fieldsInfo }) => (
						<div>
							<div>
								<For each={fieldsInfo()}>
									{(_, index) => (
										<fieldArray.Field index={index()} name="city">
											{({ field }) => (
												<div>
													<input {...field.getInputProps()} type="text" />
													<FieldErrors>
														{(errors) => (
															<div>
																{errors()
																	.flatMap((error) => error.messages)
																	.join(", ")}
															</div>
														)}
													</FieldErrors>
												</div>
											)}
										</fieldArray.Field>
									)}
								</For>
							</div>
							<div>
								<button
									onClick={() => fieldArray.push({ city: createUniqueId() })}
								>
									Push
								</button>
								<button onClick={() => fieldArray.swap(0, 1)}>Swap</button>
							</div>
						</div>
					)}
				</form.FieldArray>
			</form>
		</form.Form>
	);
}
